version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
  test:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
