vversion: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
  test:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$7dba7f12-19d7-438a-8539-e080a78434c0@git.heroku.com/$rails-app-221.git master
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
          filters:
            - branches:
                only: master
