version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
  test:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
  deploy:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      #- run:
      #  command: |
      #    git push https://git.heroku.com/shielded-crag-26870.git master
workflows:
  version: 2
  build_and_test_deploy:
    jobs:
      - build
      - test
      - deploy
